import type { Metadata } from "next";
import "./globals.css";

// Import Swiper styles
import "swiper/css";
import "swiper/css/free-mode";
import FacebookChat from "./FacebookChat";

export const metadata: Metadata = {
  title: "Nexus Marketer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <FacebookChat />
      </body>
    </html>
  );
}
