import type { Metadata } from "next";
import "./globals.css";

// Import Swiper styles
import Script from "next/script";
import "swiper/css";
import "swiper/css/free-mode";

export const metadata: Metadata = {
  title: "Nexus Marketer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}

        <div id="fb-root"></div>
        <div id="fb-customer-chat" className="fb-customerchat"></div>
        <Script id="fb-chat" strategy="lazyOnload">
          {`
          var chatbox = document.getElementById('fb-customer-chat');  
          chatbox.setAttribute("page\_id", "YOUR\_PAGE\_ID");  
          chatbox.setAttribute("attribution", "biz\_inbox");  
            
          window.fbAsyncInit = function() {  
          FB.init({  
          xfbml            : true,  
          version          : 'v12.0'  
          });  
          };  
            
          (function(d, s, id) {  
          var js, fjs = d.getElementsByTagName(s)\[0\];  
          if (d.getElementById(id)) return;  
          js = d.createElement(s); js.id = id;  
          js.src = 'https://connect.facebook.net/en\_US/sdk/xfbml.customerchat.js';  
          fjs.parentNode.insertBefore(js, fjs);  
          }(document, 'script', 'facebook-jssdk'));  
      `}
        </Script>
      </body>
    </html>
  );
}
